version: '3.0'
services:
  database:
    image: 'mongo:latest'
    container_name: lhson-ranking-db-1
    restart: always
    volumes:
      - lhson-ranking-volume:/data/db
    ports:
      - '27029:27017'
    networks:
      - lhson-ranking-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  frontend:
    build:
      context: ./frontend
    container_name: lhson-ranking-frontend-1
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - lhson-ranking-network
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    container_name: lhson-ranking-backend-1
    networks:
      - lhson-ranking-network
    ports:
      - ${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}
    environment:
      - PORT=${REACT_APP_BACKEND_PORT}
      - MONGO_URL=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_SCHEMA}?authSource=admin

networks:
  lhson-ranking-network:

volumes:
  lhson-ranking-volume: