version: '3.0'

services:
  nginx:
    build:
      context: ./fe
    volumes:
      - ./fe/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '${WEB_PORT}:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - REACT_APP_BACKEND_URL=/api
      - REACT_APP_RECORDS_PER_PAGE=${RECORDS_PER_PAGE}

  mongo:
    image: 'mongo:latest'
    restart: always
    volumes:
      - db-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  backend:
    build:
      context: ./be
    environment:
      - PORT=${BACKEND_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_SCHEMA=${MONGO_SCHEMA}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - AISERVICE_HOST=${AISERVICE_HOST}
      - AISERVICE_PORT=${AISERVICE_PORT}

  aiservice:
    build:
      context: ./ai
    environment:
      - PORT=${AISERVICE_PORT}

volumes:
  db-volume:
